name: flutter_icreserva
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^3.0.3
  mobile_scanner: ^7.1.3
  qr_flutter: ^4.1.0
  supabase_flutter: ^2.10.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/logoIC.jpg
